opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_self
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_parameters
  - no_extension_access_modifier
  - number_separator
  - operator_usage_whitespace
  - override_in_extension
  - prohibited_super_call
  - sorted_first_last
  - switch_case_alignment
  - toggle_bool
  - unavailable_function
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
disabled_rules:
  - class_delegate_protocol
  - todo
  - trailing_comma
excluded:
  - Pods
force_cast: warning
force_try:
  severity: warning
line_length: 110
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - to
    - ui
    - x
    - y
    - z
    - i